 
language: java
sudo: required
jdk:
  - openjdk8
  
cache: 
  directories:
    - $HOME/.m2
    
env:
  -DATABASE_URL=postgres://postgres:postgres@localhost:5432/alumnostip

services:
  - postgresql

before_install:
  - chmod +x mvnw
  - psql -c "CREATE DATABASE alumnostip;" -U postgres
  
install:
  - mvn clean install -DskipTests=true -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
